version: '3.7'
services: 
  db:
    image: mysql:8.0.29
    volumes: 
      - mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306