version: '3.7'
services: 
  # backend:
  #   image: node:16.16-alpine
  #   volumes: 
  #     - ./backend:/test-typeorm
  #   command: pnpm && pnpm start'
  #   environment: 
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #   ports: 
  #     - 3000:3000
  db:
    image: mysql:8.0.29
    volumes: 
      - mysql-storage:/var/lib/mysql
    environment: 
      DATABASE_HOST:
      DATABASE_NAME:
      DATABASE_USERNAME:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports: 
      - 3306:3306
volumes:
  mysql-storage: